# Site
name: 'XVA World'
title: 'XVA World'
tagline: 'All things dedicated to XVA (x-Value Adjustment) and CVA (Credit Value Adjustment)'
description: 'News and publications on XVA and CVA, open for anyone to contribute!'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'demowebsite'
email: 'contact@xva.world'
mailchimp-list: 'https://world.us14.list-manage.com/subscribe/post?u=ee98499604ccdc2b11a6e35dc&amp;id=5921c8dff0'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    alexis:
      name:           Alexis
      site:           https://www.xvaworld.com
      avatar:         assets/images/alexis.jpg
      bio:            "Alexis Bunel, programme director in Capital Market for more than 20 years of experience, with a long experience on XVA change management"
      email:          alexis@xva.world
      twitter:        https://twitter.com/xvaworld
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
